<?php

namespace CoreBundle\Repository;

use CoreBundle\Eventviva\ImageResize;

/**
 * PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository
{
    public function resize(){


    }


}
